- name: ":beetle: bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: ":blue_book: documentation"
  color: 0075ca
  description: "Improvements or additions to documentation"
- name: ":iphone: screen"
  color: 34b599
  description: "Adds a new screen to the application"
- name: ":family: duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: ":fire: enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: ":x: invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: ":grey_question: question"
  color: "d876e3"
  description: "Further information is requested"
- name: ":lock: wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: ":rocket: feature"
  color: "ccf5ff"
  description: "This adds some form of new functionality"
- name: ":boom: breaking change"
  color: "efa7ae"
  description: "This breaks existing behavior"
- name: ":sparkles: mysterious"
  color: "cccccc"
  description: "We forgot to label this"
- name: ":hammer: chore"
  color: "27127c"
  description: "Just keeping things neat and tidy"
- name: ":package: dependencies"
  color: "edc397"
  description: "Pull requests that update a dependency file"
- name: ":shipit: merge"
  color: "98ed98"
  description: "Shipit!"
- name: ":construction: deprecated"
  color: "dd824d"
  description: "Deprecated functionality"
- name: ":wastebasket: removed"
  color: "fce99f"
  description: "Removed functionality"
- name: ":old_key: security"
  color: "cbce1e"
  description: "Security related issue"
